# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           site
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://getbootstrap.com
encoding:         UTF-8

# Custom vars
current_version:  3.2.0
repo:             https://github.com/twbs/bootstrap
sass_repo:        https://github.com/twbs/bootstrap-sass

download:
  source:         https://github.com/twbs/bootstrap/archive/v3.2.0.zip
  dist:           https://github.com/twbs/bootstrap/releases/download/v3.2.0/bootstrap-3.2.0-dist.zip
  sass:           https://github.com/twbs/bootstrap-sass/archive/v3.2.0.tar.gz

groups:           https://groups.uwap.uninettlabs.no
dev:              https://dev.uwap.uninettlabs.no
uwap:
  domain:         "uwap.uninettlabs.no"

uwapdomain:       "uwap.uninettlabs.no"
