# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           site
destination:      dist
host:             0.0.0.0
port:             9001
baseurl:          /
encoding:         UTF-8


groups:           https://groups.uwap.uninettlabs.no
dev:              https://dev.uwap.uninettlabs.no
uwap:
  domain:         "feideconnect.no"

uwapdomain:       "feideconnect.no"
