# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           site
destination:      dist
host:             0.0.0.0
port:             9001
baseurl:          /
encoding:         UTF-8



apps:
  dashboard:  http://developers.feideconnect.no
  groups:     http://groups.feideconnect.no
  min:        http://min.feideconnect.no
  homepage:   http://feideconnect.no

ep:
  auth:       https://auth.feideconnect.no
  authhost:   auth.feideconnect.no
  api:        https://api.feideconnect.no
  apihost:    api.feideconnect.no
  groups:     https://api-groups.feideconnect.no

